export const tradeAreaNames = [
    'Albania',
    'Algeria',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Bermuda',
    'Bolivia (Plurinational State of)',
    'Bosnia Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Burundi',
    'Cabo Verde',
    'Cameroon',
    'Canada',
    'Chile',
    'China',
    'China, Hong Kong SAR',
    'Colombia',
    'Congo',
    'Croatia',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Dominican Rep.',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Estonia',
    'Fiji',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Guyana',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Kyrgyzstan',
    'Latvia',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malaysia',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Montenegro',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Norway',
    'Oman',
    'Other Asia, nes',
    'Pakistan',
    'Palau',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Rep. of Korea',
    'Rep. of Moldova',
    'Romania',
    'Russian Federation',
    'Saint Kitts and Nevis',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'Sao Tome and Principe',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Isds',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'TFYR of Macedonia',
    'Timor-Leste',
    'Togo',
    'Tunisia',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United Kingdom',
    'United Rep. of Tanzania',
    'Uruguay',
    'USA',
    'Zambia'
]